import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: '320px',
      sm: '375px',
      md: '480px',
      lg: '768px',
      xl: '992px',
      '2xl': '1200px',
      '3xl': '1440px',
    },
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdea5",
        "on-primary-container": "#819986",
        "on-surface-variant": "#434843",
        "surface-dim": "#dddacf",
        "surface-tint": "#4d6453",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "outline": "#737973",
        "on-primary-fixed": "#0b2013",
        "on-secondary-container": "#795d4e",
        "on-secondary": "#ffffff",
        "outline-variant": "#c3c8c1",
        "on-primary-fixed-variant": "#364c3c",
        "primary-container": "#1b3022",
        "secondary": "#74584a",
        "primary": "#061b0e",
        "tertiary-fixed-dim": "#e9c176",
        "on-tertiary-fixed-variant": "#5d4201",
        "surface-container-low": "#f7f3e8",
        "secondary-fixed": "#ffdbca",
        "primary-fixed": "#d0e9d4",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#e3bfad",
        "tertiary-container": "#3a2800",
        "inverse-primary": "#b4cdb8",
        "on-secondary-fixed": "#2a170c",
        "secondary-container": "#fed8c5",
        "on-tertiary-fixed": "#261900",
        "primary-fixed-dim": "#b4cdb8",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#1c1c15",
        "surface-container": "#f2eee3",
        "surface": "#fdf9ee",
        "surface-container-highest": "#e6e2d7",
        "surface-bright": "#fdf9ee",
        "background": "#fdf9ee",
        "surface-variant": "#e6e2d7",
        "inverse-on-surface": "#f4f0e6",
        "surface-container-high": "#ece8dd",
        "tertiary": "#211500",
        "inverse-surface": "#323129",
        "on-background": "#1c1c15",
        "on-secondary-fixed-variant": "#5a4134",
        "on-tertiary-container": "#b18d48"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Work Sans", "sans-serif"],
        "label": ["Work Sans", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Work Sans", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" }
    },
  },
  plugins: [],
};
export default config;
